version: '3.8'

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    environment:
      - TZ=Europe/Paris
    ports:
      - "${HASS_PORT:-8123}:8123"
    volumes:
      - ./ha_config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true

  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    restart: unless-stopped

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    depends_on:
      - mosquitto
    volumes:
      - ./zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    devices:
      - "${ZIGBEE_DONGLE_PATH:-/dev/ttyUSB0}:/dev/ttyUSB0"
    restart: unless-stopped

  web:
    container_name: afficheur-bus
    build: ./
    ports:
      - "${WEB_PORT:-8081}:80"
    restart: unless-stopped

volumes:
  mosquitto_data:
  mosquitto_log: