name: docker-raspberry-pi-home

services:
  web:
    container_name: afficheur-bus
    build: ./
    ports:
      - "${WEB_PORT:-8080}:80"
    restart: unless-stopped

  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./ha_config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${HASS_PORT:-8123}:8123"
    restart: unless-stopped
    privileged: true
    devices:
      - ${ZIGBEE_DONGLE_PATH:-/dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus-if00}:${ZIGBEE_DONGLE_DEVICE:-/dev/ttyUSB0}
